#--------------------------------------------
# 单节点模式编排文件，下载方式：
#
# wget https://r.datarc.cn/deploy/20220418/docker-compose.yml
#--------------------------------------------
version: '3.5'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    env_file: .env
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: always
    command: [ "redis-server", "--save", '""', "--appendonly", "no" ]
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/ch-data:/var/lib/clickhouse
  go-ws:
    image: "${WS_IMAGE}"
    restart: always
    env_file: .env
  minio:
    image: quay.io/minio/minio
    restart: always
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio-data:/data
    command: server /data --console-address ":9001"      
  web:
    image: "${CORE_IMAGE}"
    restart: always
    env_file: .env
    volumes:
      - ./configs.py:/home/code/jiaogong/configs.py
    depends_on:
      - postgres
      - redis
      - go-ws
    ports:
      - 8000:8000
    command: "gunicorn jiaogong.wsgi -c gunicorn.conf.py"
  beat:
    image: "${CORE_IMAGE}"
    restart: always
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - ./configs.py:/home/code/jiaogong/configs.py
    command: "celery --app=jiaogong beat --loglevel=INFO"
  worker:
    image: "${CORE_IMAGE}"
    restart: always
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - ./configs.py:/home/code/jiaogong/configs.py
    command: "celery --app=jiaogong worker --loglevel=INFO --concurrency=5 --events --queues=celery"
